// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALUgPGpOcrIJgNejYRgNFT1vFdrSEUxLI',
    appId: '1:1047896275225:web:90d3b35d8e681ecaf8ad88',
    messagingSenderId: '1047896275225',
    projectId: 'shopsmartar-db44f',
    authDomain: 'shopsmartar-db44f.firebaseapp.com',
    storageBucket: 'shopsmartar-db44f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulr7U3nEiWACcl_E5U2PW-T7qvnFfHTI',
    appId: '1:1047896275225:android:33f92c640b92a4b3f8ad88',
    messagingSenderId: '1047896275225',
    projectId: 'shopsmartar-db44f',
    storageBucket: 'shopsmartar-db44f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCij8BJWX4kipCtMEd1-XP4s6OQGZQEemE',
    appId: '1:1047896275225:ios:eb49f304f51b359ef8ad88',
    messagingSenderId: '1047896275225',
    projectId: 'shopsmartar-db44f',
    storageBucket: 'shopsmartar-db44f.appspot.com',
    androidClientId: '1047896275225-go5q2phaq0ivh28fu1q6rn4tjfig9ulo.apps.googleusercontent.com',
    iosClientId: '1047896275225-bu36kn2sh2vs46cldb4u5osckghb6hv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCij8BJWX4kipCtMEd1-XP4s6OQGZQEemE',
    appId: '1:1047896275225:ios:eb49f304f51b359ef8ad88',
    messagingSenderId: '1047896275225',
    projectId: 'shopsmartar-db44f',
    storageBucket: 'shopsmartar-db44f.appspot.com',
    androidClientId: '1047896275225-go5q2phaq0ivh28fu1q6rn4tjfig9ulo.apps.googleusercontent.com',
    iosClientId: '1047896275225-bu36kn2sh2vs46cldb4u5osckghb6hv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALUgPGpOcrIJgNejYRgNFT1vFdrSEUxLI',
    appId: '1:1047896275225:web:fb08901d02b85ed9f8ad88',
    messagingSenderId: '1047896275225',
    projectId: 'shopsmartar-db44f',
    authDomain: 'shopsmartar-db44f.firebaseapp.com',
    storageBucket: 'shopsmartar-db44f.appspot.com',
  );
}
